### ISSUE TITLE
Error running the example command in README.

### ISSUE THREAD

**Issue by gusaiani** [twined/eightyfour#2]
Hello @tmjoen,

I tried setting up my project following the instructions in the README.

I'm getting the following error:

```
GenServer Eightyfour.TokenCache terminating
** (UndefinedFunctionError) function :certifi.cacerts/0 is undefined (module :certifi is not available)
    (certifi) :certifi.cacerts()
```

Is this repo still maintained? Would you be interested in helping out a fellow Elixirist with this? :)

Many thanks!
Gustavo

**Comment by gusaiani** [comment]
Ok, the `certify` issue is related to Hackney.

I kind of fixed it, it's unstable but now I'm querying the browsers and it's returning 

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream, Timex.Interval
    (elixir) /private/tmp/elixir-20180825-41637-j0b7x7/elixir-1.7.3/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20180825-41637-j0b7x7/elixir-1.7.3/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:2979: Enum.reduce/3
    (eightyfour) lib/eightyfour/queries.ex:42: Eightyfour.Query.browsers/1
```

this is a pretty large Analytics history.

Thoughts?

**Comment by tmjoen** [comment]
Strange, I pulled it up now and everything seems to work for me. 

```elixir
Eightyfour.Query.browsers(:yesterday)
[
  [os: "Windows", browser: "Chrome", version: "69.0.3497.100", hits: "201"],
  [os: "iOS", browser: "Safari", version: "11.0", hits: "177"]
...
]
```

I've pushed some updates to the repo with updated deps — you could try it with

`{:eightyfour, github: "twined/eightyfour"}` in your `mix.exs`

What version of erlang are you running?

**Comment by gusaiani** [comment]
Hey @tmjoen, 

thanks for your response. I ended up having twins since I wrote haahhaahah

I'll get back to you as soon as I can here.

All the best!

**Comment by tmjoen** [comment]
Hah, no worries. Congratulations, you're gonna need all the concurrency you can get!
